### PR TITLE
Some man page improvements

### LINKED ISSUE #101: `flashmq` its command-line options are not documented in its man page
None of `flashmq` its command-line options are described in its man page. I noticed this when I tried to find the default `--config-file` location there.

I'm intending to fill in this small gap in a PR to come.

### PR DESCRIPTION
**Pull request by bigsmoke**
Resolves #101, among other things.

### CODE REVIEW

**Comment by halfgaar** [comment]
There are some issues. First small:

flashmq_man_Screenshot_20240512_091614

Then, there are merge mistakes:

flashmq_man2_Screenshot_20240512_091943

This is also reflected by:

```
touch *.dbk5 ; make
xsltproc db5to4/db5to4-withinfo.xsl flashmq.1.dbk5 > flashmq.1.dbk4
flashmq.1.dbk5:80: element varlistentry: validity error : ID SIGHUP already defined
    <varlistentry xml:id="SIGHUP">
                                 ^
flashmq.1.dbk5:113: element varlistentry: validity error : ID SIGUSR2 already defined
      <varlistentry xml:id="SIGUSR2">

etc
```

**Comment by bigsmoke** [comment]
I used an EM space as a workaround for the missing space between `-c` and `config_file_path` in `flashmq(1)` .

I also fixed another mistake that I overlooked yesterday.

Apologies for the merge errors. It was a messy rebase due to the whitespace changes that occurred when I added the missing `<variablelist>` container and increased the indent of its contents. I ended up using `-Xours`, but, clearly, with insufficient checking, though I was convinced I had been rather thorough.

**Comment by halfgaar** [comment]
> I used an EM space as a workaround for the missing space between `-c` and `config_file_path` in `flashmq(1)` .

Yeah, that docbook2x is not perfect...

> 
> I also fixed another mistake that I overlooked yesterday.
> 
> Apologies for the merge errors. It was a messy rebase due to the whitespace changes that occurred when I added the missing `<variablelist>` container and increased the indent of its contents. I ended up using `-Xours`, but, clearly, with insufficient checking, though I was convinced I had been rather thorough.

Technically it's not correct yet. [This commit](https://github.com/bigsmoke/FlashMQ/commit/b4ad541bc8cb3296abb342ea052cead6574e325f) copies sections (`SIGHUP` and `SIGUSR` appear twice; github's diff viewer doesn't readily show it, without pressing 'expand all') that are removed again later. The end result looks good, but I'd rather have the commits correct.

**Comment by bigsmoke** [comment]
Ah, yeah. Thanks for triple-checking me! I've done a thorough `git rebase --interactive origin/master`, editing each commit in turn, including a `make -C man` to make sure that also the generated stuff is correct at each commit. (It wasn't for one of the commits.)

**Comment by halfgaar** [comment]
Merged in :+1:

**Pull request closed without merging**
