### PR TITLE
Some small docstring tweaks

### PR DESCRIPTION
**Pull request by bigsmoke**

### CODE REVIEW

**Comment by halfgaar** [comment]
Thanks for your contribution. The long term plan is to write many class/method docs, even it's somewhat obvious what the code does, so this contribution is appreciated. I did change it a bit though, outside Github. And Github's master was a little behind (I pushed it now), so I rebased it, locally.

Your author is only your first name. Do you want me to keep it that way, or amend it? No need/point to amend your PR, because my local work is done and pending push already.

**Comment by bigsmoke** [comment]
Just first name is fine. I might change it for future commits, but I don't care for now.

**Comment by halfgaar** [comment]
I pushed the commit, with my alterations.

**Comment by bigsmoke** [comment]
Just first name is fine. I might change it for future commits, but I don't
care for now.

**Pull request closed without merging**
