### PR TITLE
Man-page improvements, including the ditchting of `docbook2x`

### PR DESCRIPTION
**Pull request by bigsmoke**
The only dependency that is now left for building the man-pages is an XSLT processor. (The `Makefile` assumes `xsltproc`.)

### CODE REVIEW

**Comment by halfgaar** [comment]
I don't quite understand [Add missing <variablelist> container el](https://github.com/halfgaar/FlashMQ/pull/106/commits/09cdb096edb05ba338f5ff6696ac113eeaf51166) and [Document command-line args & cross ref. config stuff](https://github.com/halfgaar/FlashMQ/pull/106/commits/2febd234f3d97cc9d3d7766c69464974b2e6c675). It's the same duplication of sections and stuff we saw before?

**Comment by halfgaar** [comment]
This is so cool:

image

I would like to frame it...

Too bad Debian turns the colors off by default, so few people will see it.

There is a slight generation problem in the html version though:

image

Both literals name `flashmq.conf` as stray string.

**Comment by bigsmoke** [comment]
Good catch! I've changed that template to only `<xsl:apply-templates select="text()"/>`, instead of `node()`. Previously, the attribute would be caught by `node()` and processed by the default template, and this only became noticeable with the extra attribute.

By the way: I have not (yet) implemented syntax highlighting for HTML. I'm inclined to use the same (XSLT-based) method, since all the XSLT is bound to this project anyway and I thus see no need for the use of a more general-purpose syntax-highlighting method.

**Comment by halfgaar** [comment]
It's merged :+1:

**Pull request merged**
